version: "3"

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=instagram_rs
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    volumes:
      - insta_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - insta-network

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - insta-network

networks:
  insta-network:

volumes:
  insta_data:
